project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: ./notebooks/quarto-style/style.css
    highlight-style: atom-one
    mainfont: Palatino
    fontcolor: black
    monobackgroundcolor: white
    monofont: Menlo, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace
    fontsize: 13pt
    linestretch: 1.4
    toc: true
    toc-location: right
    toc-depth: 4
    code-fold: true
    code-copy: true
    cap-location: bottom
    format-links: false
    embed-resources: true
    anchor-sections: true
    html-math-method: katex
    # html-math-method:
    #   method: mathjax
    #   url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    code-links:
      - text: GitHub Repo
        icon: github
        href: https://github.com/abdullahau/investment-portfolio/
      - text: Quarto Markdown
        icon: file-code
        href: https://github.com/abdullahau/investment-portfolio/blob/main/
